version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestjsdb
      MYSQL_USER: nestjsuser
      MYSQL_PASSWORD: nestjspassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  nestjs-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: nestjsuser
      DB_PASSWORD: nestjspassword
      DB_NAME: nestjsdb
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
